### ISSUE TITLE
Plugin does not work if CSRF protection is enabled

### ISSUE THREAD

**Issue by mildlygeeky** [carlcs/craft-deleteallentryversions#1]
I've had this happen on my own plugins that POST to a controller action — is CSRF protection is enforced, then it causes the request to not work.

I am getting the following when trying to run the plugin:

Bad Request
The CSRF token could not be verified.

Unfortunately, I don't think there is a great way around this, other than making the controller not POST (http://craftcms.stackexchange.com/questions/4553/whats-the-best-way-to-skip-csrf-for-plugin-controllers).

**Comment by carlcs** [comment]
Added CSRF Protection support in 1.0.3. Thanks Patrick!
