### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by m8brgarc** [carlcs/craft-deleteallentryversions#3]
It doesn't seem to work with the most current version of craft.  Am I doing something wrong?  I simply installed it, went to the settings and clicked the Delete Entry Versions button.

**Comment by carlcs** [comment]
The plugin deletes all versions but the most current one. This is necessary to be able to revert back to that version once a new version is saved.

**Comment by carlcs** [comment]
@m8brgarc why do you want to see the current version being deleted?

**Comment by m8brgarc** [comment]
Ah no, I think you are misunderstanding me.  I was saying that the plugin is not working on the most current version of Craft CMS.  It doesn't delete any entry versions at all.

**Comment by carlcs** [comment]
Turned out @m8brgarc was using the plugin on a Craft Personal install, whereas the plugin required at least Craft Client (versions didn’t exist for Craft Personal pre Craft 2.??).

Anyways, I removed that restriction in v1.1.1
