### ISSUE TITLE
Not working with Craft 3? Missing database table 'entryversions'

### ISSUE THREAD

**Issue by ramonleenders** [carlcs/craft-deleteallentryversions#6]
I am getting an SQL error when trying to delete versions, guessing because this table is not existing in Craft version 3 and versions stored on some other way.

```SQLSTATE[42S02]: Base table or view not found: 1146 Table 'entryversions' doesn't exist
The SQL being executed was: SELECT `e`.`id`
FROM `entryversions` `e`
INNER JOIN (SELECT `entryId`, `siteId`, max(dateCreated) AS `MaxDateCreated`
FROM `entryversions`
GROUP BY `entryId`, `siteId`) `g` ON (e.entryId = g.entryId) AND (e.siteId = g.siteId) AND (e.dateCreated = g.MaxDateCreated)```

**Comment by zzseba78** [comment]
Same problem, useless.

**Comment by ramonleenders** [comment]
@carlcs You're not going to develop this any further?

**Comment by carlcs** [comment]
Sorry for the late response. The plugin has become obsolete with the release of Craft 3.2, which added the [`maxRevisions`](https://docs.craftcms.com/v3/config/config-settings.html#maxrevisions) config setting to limit the number of revisions stored for each element. Craft 3.4 added the [`utils/prune-revisions`](https://github.com/craftcms/cms/blob/develop/CHANGELOG-v3.md#340---2020-01-28) command to delete revisions from the console.

I have also updated the composer requirements, so the package won’t install on projects with `craftcms/cms` >= 3.2 any longer.

**Comment by ramonleenders** [comment]
OK, cheers. Thanks for this info!
